include fonts/victor-font.conf
include current-theme.conf
include basic.conf

# =================
# 交互功能设置
# =================

# 启用远程控制（主题切换、Sessions必需）
allow_remote_control yes

# Kitty 默认启用滚动条，可通过以下选项自定义
scrollbar_width 1
scrollbar_fg #666666
scrollbar_bg #1e1e2e

# 多光标编辑
map ctrl+shift+up add_cursor_up
map ctrl+shift+down add_cursor_down

# 透明背景设置
background_opacity 0.90
dynamic_background_opacity yes

# 复制粘贴优化
copy_on_select yes
strip_trailing_spaces smart

# =================
# Kitty快捷键映射配置
# =================
# 窗口分割（kitty快捷键核心功能）
# 向下开启新窗口
map ctrl+d launch --location=hsplit --before
# 向右开启新窗口
map ctrl+r launch --location=vsplit --before
map ctrl+w close_window
# 在分屏窗口间切换
map ctrl+[ previous_window
map ctrl+] next_window

# 关闭音效
enable_audio_bell no
